### PR TITLE
Pressing ESC to close "Alert Dialog"

### PR DESCRIPTION
**Pull request by felipebueno**
I think many users like to close dialogs pressing ESC. Let me know if it is useful.

### CODE REVIEW

**Comment by fabien-d** [comment]
I like it - could you squash your commits and then I'll merge?

**Comment by fabien-d** [comment]
It is not standard behaviour of native alert() dialogs... but I'm still leaning towards it. I think it makes sense from a user perspective (even if it's not a modal window, which are what people tend to close with ESC)

**Comment by felipebueno** [comment]
Fabien-d, how do I that (to squash my commits)? I am a git noob yet heheh

**Comment by fabien-d** [comment]
I generally rebase (if the code hasn't be pushed - otherwise conflicts can occur)

```
git rebase -i HEAD~3
```

3 is the number of commits to go back on. http://git-scm.com/book/en/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages

then squash comits onto each other

```
pick ...
squash ...
squash ...
```

http://git-scm.com/book/en/Git-Tools-Rewriting-History#Squashing-Commits

**Pull request closed without merging**
