### PR TITLE
WIP - Version 0.5.0

### PR DESCRIPTION
**Pull request by fabien-d**
The todo list will be growing...
### Alert
- [x] Set passed title message
- [x] OK button
### Confirm
- [x] Set passed title message
- [x] OK button
- [x] Cancel button
### Prompt
- [x] Set passed title message
- [x] OK button
- [x] Cancel button
- [x] Input field
- [x] Set default input field value
### Common
- [ ] Finalize base theme. #187
- [x] Set proper `alertify--TYPE` class name
- [x] Handle attempt to open multiple dialogs at one time.
- [x] Keep focus inside dialog
- [x] Reset the focus to the last focused element before the dialog was open
- [x] Show cover when dialog opens
- [ ] Update ARIA attributes based on state
- [x] Keyboard shortcut - ESC = cancel, Enter = OK
### Questions
- [ ] Add growl notifications? Or open separate repo...
- [ ] Allow dialogs to queue? #174

---

**This PR will most likely be long running and changing over time.**

---
### Alert

image
### Confirm

image
### Prompt

image
## New API & Usage

Only supports dialog at the moment. I am thinking of moving the growl notification into its own project. `0.5.0` moves away from dynamically creating the alert dialogs and now includes the markup directly in the page.
### Usage

``` html
<!-- in the head tag -->
<link rel="stylesheet" href="PATH_TO/alertify.core.css">
<link rel="stylesheet" href="PATH_TO/alertify.default.css">

<!-- preferably just before the closing body tag -->
<div id="alertifyCover" class="alertify-cover alertify-hidden" aria-hidden="true"></div>
<section id="alertifyDialog" class="alertify alertify-close" aria-labelledby="alertifyTitle" aria-hidden="true">
    <div class="alertify-body">
        <p id="alertifyTitle" class="alertify-title"></p>
        <input type="text" id="alertifyInput" class="alertify-input" aria-hidden="true">
        <nav id="alertifyButtons" class="alertify-buttons">
            <button id="alertifyButtonCancel" class="alertify-button alertify-button-cancel" aria-hidden="true"></button>
            <button id="alertifyButtonOk" class="alertify-button alertify-button-ok" aria-hidden="true"></button>
        </nav>
        <a id="alertifyFocusReset" class="alertify-focus-reset" href="#" aria-hidden="true"></a>
    </div>
</section>

<script src="PATH_TO/alertify[.min].js"></script>
```
### Alert

``` js
// basic
alertify.alert( 'Title' ).show();

// advanced
var alert = alertify.alert( 'Title' );
alert.ok = function () {
    // OK
};
alert.show();
```
### Confirm

``` js
// basic
alertify.confirm( 'Title' ).show();

// advanced
var confirm = alertify.confirm( 'Title' );
confirm.ok = function () {
    // OK
};
confirm.cancel = function () {
    // Cancel
};
confirm.show();
```
### Prompt

``` js
// basic
alertify.prompt( 'Title' ).show();

// advanced
var prompt = alertify.prompt( 'Title' );
prompt.ok = function ( val ) {
    // OK
    // val => Value of input field
};
prompt.cancel = function () {
    // Cancel
};
prompt.show();
```
### Extra methods

A few extra methods are available on each dialog.

``` js
var alert = alertify.alert( 'Title' );
alert.onshow = function () {
    // called on dialog show
};
alert.onclose = function () {
    // called on dialog closed
};
alert.onfocus = function () {
    // called after focus to element has been set
};

alert.show(); // shows the dialog

// close() is available if a dialog must be closed programmatically, 
// it's automatically call on click of a button
alert.close(); // closes the dialog
```

### CODE REVIEW

**Comment by fritx** [comment]
Any idea to make a dialog which provides certain items to select? :smile:

**Comment by fabien-d** [comment]
> Any idea to make a dialog which provides certain items to select

That's more of a modal than a dialog. The intention of this library is to replace the native dialogs so at this time that would not really be possible.

**Comment by fritx** [comment]
@fabien-d thanks it's pretty kind of your stuff to be responsive on a mobile phone :laughing:

**Comment by ValsiS** [comment]
when do you think you will make first relase of this version ? because i want to use it in a project ...

**Comment by fritx** [comment]
Yes, when can I just install it thro bower?

**Comment by fabien-d** [comment]
I'm going to try to get some bug fixes for `0.3` today and if I get a chance I'll try to release a `0.5.0rc1` as well.

**Comment by fritx** [comment]
Sorry to have registered an entry `alertify-v0.5` in bower...
I don't know how to undo it.

**Comment by fabien-d** [comment]
there is no way to unregister at this time, see: https://github.com/bower/bower/issues/120

**Comment by fabien-d** [comment]
Closing. Created - [0.5 branch](https://github.com/fabien-d/alertify.js/tree/0.5)

**Comment by fritx** [comment]
Yeah I posted my will.
I registered the 0.5 branch as https://github.com/weixinjs/alertify.js to Bower.

**Comment by fabien-d** [comment]
Released `0.5.0rc1`. Usage example can be found [here](https://github.com/fabien-d/alertify.js/wiki/0.5----Usage).

More documentation and an example site will be up shortly

**Comment by fritx** [comment]
Fine. :+1: 
By the way, I find the new dialog is too white, to fit some white background,
a bit eye-harming, any way to solve that?

**Comment by fabien-d** [comment]
> I find the new dialog is too white

Agreed. I have an issue opened for it (https://github.com/fabien-d/alertify.js/issues/187) was hoping to get a designer to coming in and help out. Even if only with a visual and not code

**Comment by yuvii** [comment]
Is there any intent to expand the API? I'm currently using 0.3.11. While the library is fantastic, the API is kinda limited and I find myself messing with the source code attempting to customize certain features (such as changing the animation style, customizing alert positioning, etc.)

**Comment by fabien-d** [comment]
> such as changing the animation style, customizing alert positioning

alertify.js was built so only the core was in the JS. These two items are controlled via CSS. The original goal was to build a theme library which would cover various animations and positions but I just never had time or contributions for it -

**Comment by fritx** [comment]
> The original goal was to build a theme library which would cover various animations and positions

agreed. :+1:

**Comment by mako0403** [comment]
0.5 When officially released？

**Pull request closed without merging**
