### PR TITLE
Added component.json for Bower

### PR DESCRIPTION
**Pull request by toin0u**
Hi Fabien,

What do you think to add your library to [Bower](http://twitter.github.com/bower/) ?

You just need to tag and register to Bower:

``` bash
$ git tag 0.2.9
$ bower register alertify git://github.com/fabien-d/alertify.js.git
```

I've tested with a bare repo. It works pretty well :+1: 

Regards.

### CODE REVIEW

**Comment by fabien-d** [comment]
This would be a nice feature - it's already possible to use with bower without the component.json, you just need the full git url, which I know isn't ideal.

```
$ bower install git://github.com/fabien-d/alertify.js.git
```

The bower documentation says [there should only be at most one file per file type in the main list](https://github.com/twitter/bower#defining-a-package).

I'm thinking I may create a separate shim repo similar to what the [github components](https://github.com/components) has, and serve alertify from there. That way it's separate and only serves the files needed. 

It would require a bit of thinking since I'm hoping to expand the theme options to more than just the alertify.default.css.

I've assigned this to the 0.3.0 milestone.

**Comment by toin0u** [comment]
Yes it's possible to use with the full git url. But as you wrote it isn't ideal. I'm glad to know that you'll implement this for the next milestone.

I think the shim repo is a great idea.

**Comment by fabien-d** [comment]
Closing this pull request. I've registered `alertify` as a bower package and pointed it to the shim repo https://github.com/fabien-d/alertify.js-shim.

Thanks for the suggestion.

**Comment by toin0u** [comment]
:+1:

**Pull request closed without merging**
