### PR TITLE
Bootstrap 3 theme added (0.3)

### PR DESCRIPTION
**Pull request by dbtek**
Styles fit Bootstrap v3 added with this theme.

### CODE REVIEW

**Comment by fabien-d** [comment]
Thanks - I'll take a closer look when I get a few mins. Could you fix the indentation, tabs, so it is consistent and matching the current `0.3` formatting.

**Comment by dbtek** [comment]
Actually, there is the indentation like the older Bootstrap theme.

**Comment by fabien-d** [comment]
There is some indentation issues - e.g.

image

and

image

Otherwise it looks good.

**Comment by fabien-d** [comment]
If you do format the code feel free to reopen the PR. I will merge, but only if it's following the code standards, cheers

**Pull request closed without merging**
