### PR TITLE
Same changes as previous PR

### PR DESCRIPTION
**Pull request by quasipickle**
It was easier to start from scratch than fart around with the various git commands.

### CODE REVIEW

**Comment by fabien-d** [comment]
Tying to https://github.com/fabien-d/alertify.js/pull/87 to keep the conversation around this PR. Two quick things (and then I'm done - I swear):
1. Could you re-insert https://github.com/fabien-d/alertify.js/pull/87/files#L0R36 back? That was a great catch
2. Could you update your single quotes to double quotes (for consistency)

Don't worry about squashing - 2 commits is fine. Also feel free to add your info in the Contributors.md file in the root.

Once that's in - I'll merge! 

Cheers

**Comment by quasipickle** [comment]
Done.  I saw the extra /> again, but neglected to process that the / shouldn't be there.

**Comment by fabien-d** [comment]
Appreciate the back and forth... I'm going to test it when I get home, and it will be part of the next minor version bump. Cheers

**Comment by quasipickle** [comment]
I have no problem tweaking code to fit formatting preferences.  It makes perfect sense.  I was just getting frustrated with the seemingly arcane knowledge that was seemingly required to make a seemingly simple commit.  Or so it seemed.

**Pull request merged**
