### PR TITLE
quick fix for #152: allow users to style dialog types individually

### PR DESCRIPTION
**Pull request by flosell**
I added the type to the class-name of alertify-dialog-inner. this way, the user can style only one dialog differently: 

```
.alertify-dialog-inner-alert {
  background-color: red;
  padding: 25px; 
}
.alertify-dialog-inner-confirm,
.alertify-dialog-inner-prompt {
  padding: 25px; 
}
```

By the way: The grunt-build wasn't working for me: 

```
   Tracing dependencies for: alertify
   [Error: TypeError: Cannot read property '0' of null
       at Object.grunt.initConfig.requirejs.compile.options.onBuildWrite (<mypath>alertify.js/Gruntfile.js:115:44)
   ]
```

After adding a null-check, it worked fine enough to get build-results but the created `alertify.(min).js` had some errors.

### CODE REVIEW

**Comment by fabien-d** [comment]
The build was fix with #154 so you can pull down the latest master branch and should be able to run grunt.

Also, this functionality exists in `0.3.*`, it just hasn't been ported over to `0.4` yet, so I would like to keep it consistent with where the type gets appended.

See https://github.com/fabien-d/alertify.js/blob/0.3/src/alertify.js#L286 and screenshot:

image

**Comment by flosell** [comment]
gave it another try: 
image

**Comment by fabien-d** [comment]
There's conflicts in the PR. The change looks good, I would just rather have spacing around the blocks for legibility and consistency. Also, once the conflict is resolved, could you squash your commits?

``` js
// from:
clsElShow+" "+"alertify-"+item.type 
// to:
clsElShow + " " + "alertify-" + item.type
```

**Comment by flosell** [comment]
Sorry, I committed the minified code, that obviously led to conflicts... 
Created a new, clean pull-request: #155

**Comment by fabien-d** [comment]
committing minified source shouldn't create conflicts - but it can be a pain. I've been debatting whether to remove them from source control and I think I will. Closing since you opened a new PR

**Pull request closed without merging**
